import { SectorCode } from "./sectors";

export type GHGScope = 1 | 2 | 3;

export interface GHGCategory {
  id: string;
  scope: GHGScope;
  number: number;
  name: string;
  description: string;
  defaultSector: SectorCode;
  examples: string[];
}

// Scope 1: Direct emissions
export const SCOPE1_CATEGORIES: GHGCategory[] = [
  {
    id: "scope1_stationary",
    scope: 1,
    number: 1,
    name: "Stationary Combustion",
    description: "Fuel burned in owned/controlled boilers, furnaces, turbines",
    defaultSector: "ENERGY",
    examples: ["Natural gas for heating", "Diesel generators"],
  },
  {
    id: "scope1_mobile",
    scope: 1,
    number: 2,
    name: "Mobile Combustion",
    description: "Fuel burned in owned/controlled vehicles and equipment",
    defaultSector: "TRANSPORT",
    examples: ["Company fleet vehicles", "Forklifts", "Aircraft (if owned)"],
  },
  {
    id: "scope1_process",
    scope: 1,
    number: 3,
    name: "Process Emissions",
    description: "Emissions from industrial processes (non-combustion)",
    defaultSector: "MANUFACTURING",
    examples: ["Cement clinker production", "Chemical reactions"],
  },
  {
    id: "scope1_fugitive",
    scope: 1,
    number: 4,
    name: "Fugitive Emissions",
    description: "Leaks from equipment (refrigerants, SF6, methane)",
    defaultSector: "GENERAL",
    examples: ["Refrigerant leaks", "SF6 from switchgear"],
  },
];

// Scope 2: Indirect emissions from purchased energy
export const SCOPE2_CATEGORIES: GHGCategory[] = [
  {
    id: "scope2_electricity",
    scope: 2,
    number: 1,
    name: "Purchased Electricity",
    description: "Indirect emissions from purchased electricity consumption",
    defaultSector: "ENERGY",
    examples: ["Grid electricity for offices and facilities"],
  },
  {
    id: "scope2_heat",
    scope: 2,
    number: 2,
    name: "Purchased Heat & Steam",
    description: "Indirect emissions from purchased heating, cooling, and steam",
    defaultSector: "ENERGY",
    examples: ["District heating", "Purchased steam for processes"],
  },
  {
    id: "scope2_cooling",
    scope: 2,
    number: 3,
    name: "Purchased Cooling",
    description: "Indirect emissions from purchased cooling",
    defaultSector: "ENERGY",
    examples: ["District cooling systems"],
  },
];

// Scope 3: Value chain emissions (15 categories per GHG Protocol)
export const SCOPE3_CATEGORIES: GHGCategory[] = [
  {
    id: "scope3_cat1",
    scope: 3,
    number: 1,
    name: "Purchased Goods & Services",
    description: "Upstream emissions from production of goods and services purchased",
    defaultSector: "GENERAL",
    examples: ["Office supplies", "IT equipment", "Professional services"],
  },
  {
    id: "scope3_cat2",
    scope: 3,
    number: 2,
    name: "Capital Goods",
    description: "Upstream emissions from production of capital goods purchased",
    defaultSector: "MANUFACTURING",
    examples: ["Machinery", "Vehicles", "Buildings", "Equipment"],
  },
  {
    id: "scope3_cat3",
    scope: 3,
    number: 3,
    name: "Fuel- & Energy-Related Activities",
    description: "Emissions from fuel/energy not in Scope 1 or 2 (upstream of fuels, T&D losses)",
    defaultSector: "ENERGY",
    examples: ["Extraction and refining of fuels", "T&D losses"],
  },
  {
    id: "scope3_cat4",
    scope: 3,
    number: 4,
    name: "Upstream Transportation & Distribution",
    description: "Emissions from transport of purchased goods (paid by reporting company)",
    defaultSector: "TRANSPORT",
    examples: ["Freight shipping", "Third-party logistics"],
  },
  {
    id: "scope3_cat5",
    scope: 3,
    number: 5,
    name: "Waste Generated in Operations",
    description: "Emissions from disposal/treatment of waste generated by operations",
    defaultSector: "GENERAL",
    examples: ["Landfill", "Recycling", "Wastewater treatment"],
  },
  {
    id: "scope3_cat6",
    scope: 3,
    number: 6,
    name: "Business Travel",
    description: "Emissions from employee travel for business in vehicles not owned",
    defaultSector: "AVIATION",
    examples: ["Flights", "Rail travel", "Hotel stays", "Rental cars"],
  },
  {
    id: "scope3_cat7",
    scope: 3,
    number: 7,
    name: "Employee Commuting",
    description: "Emissions from employees commuting between home and work",
    defaultSector: "TRANSPORT",
    examples: ["Driving to work", "Public transit", "Remote work energy"],
  },
  {
    id: "scope3_cat8",
    scope: 3,
    number: 8,
    name: "Upstream Leased Assets",
    description: "Emissions from operation of leased assets (not in Scope 1/2)",
    defaultSector: "GENERAL",
    examples: ["Leased office space", "Leased vehicles"],
  },
  {
    id: "scope3_cat9",
    scope: 3,
    number: 9,
    name: "Downstream Transportation & Distribution",
    description: "Emissions from transport of sold products (not paid by reporting company)",
    defaultSector: "TRANSPORT",
    examples: ["Delivery to customers", "Retail distribution"],
  },
  {
    id: "scope3_cat10",
    scope: 3,
    number: 10,
    name: "Processing of Sold Products",
    description: "Emissions from processing of intermediate products by downstream companies",
    defaultSector: "MANUFACTURING",
    examples: ["Further processing by customers", "Assembly operations"],
  },
  {
    id: "scope3_cat11",
    scope: 3,
    number: 11,
    name: "Use of Sold Products",
    description: "Emissions from end use of goods and services sold",
    defaultSector: "GENERAL",
    examples: ["Vehicle fuel combustion", "Electricity use of appliances", "Cement use in buildings"],
  },
  {
    id: "scope3_cat12",
    scope: 3,
    number: 12,
    name: "End-of-Life Treatment of Sold Products",
    description: "Emissions from disposal of products sold by the reporting company",
    defaultSector: "GENERAL",
    examples: ["Recycling", "Landfill", "Incineration"],
  },
  {
    id: "scope3_cat13",
    scope: 3,
    number: 13,
    name: "Downstream Leased Assets",
    description: "Emissions from operation of assets owned and leased to others",
    defaultSector: "GENERAL",
    examples: ["Leased real estate", "Leased equipment"],
  },
  {
    id: "scope3_cat14",
    scope: 3,
    number: 14,
    name: "Franchises",
    description: "Emissions from operation of franchises",
    defaultSector: "GENERAL",
    examples: ["Franchise store energy use", "Franchise fleet emissions"],
  },
  {
    id: "scope3_cat15",
    scope: 3,
    number: 15,
    name: "Investments",
    description: "Emissions from operation of investments (equity, debt, project finance)",
    defaultSector: "GENERAL",
    examples: ["Equity investments", "Project finance", "Managed assets"],
  },
];

export const ALL_GHG_CATEGORIES: GHGCategory[] = [
  ...SCOPE1_CATEGORIES,
  ...SCOPE2_CATEGORIES,
  ...SCOPE3_CATEGORIES,
];

export function getGHGCategory(id: string): GHGCategory | undefined {
  return ALL_GHG_CATEGORIES.find((c) => c.id === id);
}

export function getCategoriesByScope(scope: GHGScope): GHGCategory[] {
  return ALL_GHG_CATEGORIES.filter((c) => c.scope === scope);
}

export function getCategoryLabel(id: string): string {
  const cat = getGHGCategory(id);
  if (!cat) return id;
  if (cat.scope === 3) return `Scope 3, Cat. ${cat.number}: ${cat.name}`;
  return `Scope ${cat.scope}: ${cat.name}`;
}

export const SCOPE_LABELS: Record<GHGScope, string> = {
  1: "Scope 1 — Direct Emissions",
  2: "Scope 2 — Indirect (Energy)",
  3: "Scope 3 — Value Chain",
};

export const SCOPE_COLORS: Record<GHGScope, string> = {
  1: "#ef4444", // red
  2: "#f59e0b", // amber
  3: "#3b82f6", // blue
};
